server:
  port: 8080
  servlet:
    context-path: /tenpo
spring:
  application:
    name: calculate-service
  datasource:
    url: ${TENPO_JDBC_URL:jdbc:postgresql://localhost:5432/tenpo}
    username: ${TENPO_JDBC_USER:tenpo}
    password: ${TENPO_JDBC_PASS:root}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
tenpo:
  app:
    percentageCron: "0 */30 * * * *"
otherApp:
  url:
    api: https://somepage.com.cl/
application:
  clientApp:
    name: TenpoApp
logging:
  level:
    org:
      hibernate:
        sql: debug